name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Maven Run Unit Test
        run: mvn -B clean test
      - name: Maven Run Integeration Test
        run: mvn -B verify -Pintegration-tests